on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release to GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-rustup
        with:
          path: ~/.cache/rustup/
          key: ${{ runner.os }}-rustup
      - name: rustup
        run: |
          rustup toolchain install stable
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt

      - name: Build v86
        run: make build/libv86.js build/v86.wasm build/v86-fallback.wasm

      - name: Release to GitHub
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Latest Release
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            build/*.js
            build/*.js.map
            build/*.wasm
